# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
default: &default
  mailer_authentication: <%= ENV['MAILER_AUTHENTICATION'] %>
  mailer_port: <%= ENV['MAILER_PORT'] %>
  mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
  mailer_password: <%= ENV['MAILER_PASSWORD'] %>
  mailer_user_name: <%= ENV['MAILER_USER_NAME'] %>
  mailer_address: <%= ENV['MAILER_ADDRESS'] %>

development:
  <<: *default
  secret_key_base: d0d5b945d0434e819f95195d0123259786b5251a8ed00048950af8192c549904db96cced4b2793ceeaabc5cf2a235ab1ed62387f7c37cfca1b590105f2475226

test:
  <<: *default
  secret_key_base: 72b9e883cc1146d7bb2f44071ffacd1eec62a56fbce607757e5223403f7ff3280d08cfa770b22362fe26e7b617962227b011fdab9be70a050b37e1e10fbb7b2f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
